version: "3.7"

x-http-proxy: &http-proxy ${HTTP_PROXY}
x-https-proxy: &https-proxy ${HTTPS_PROXY}
x-no-proxy: &no-proxy localhost,127.0.0.1,uclvlddpragae08
x-proxy-common: &proxy-common
  HTTP_PROXY: *http-proxy
  http_proxy: *http-proxy
  HTTPS_PROXY: *https-proxy
  https_proxy: *https-proxy
  NO_PROXY: *no-proxy
  no_proxy: *no-proxy


services:
    redis:
      image: redis
      ports:
          - "6379:6379"
      volumes:
          - ./app:/code/app
      networks:
          - gpcnet

    gpcon:
      build:
          context: .
          args:
              <<: *proxy-common
      ports:
          - "7654:80"
      environment:
          <<: *proxy-common
      networks:
          - gpcnet

networks:
  gpcnet:

